apiVersion: v1
kind: Service
metadata:
  name: scanner
  namespace: aqueduct
spec:
  selector:
    app: scanner
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: aqueduct
    port: 6476
    targetPort: 6476
---
apiVersion: v1
kind: Service
metadata:
  name: scannerpublic
  namespace: aqueduct
  annotations:
    "git.andyleap.dev/singress-target": "scanner.andyleap.dev"
spec:
  selector:
    app: scannerpublic
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
  namespace: aqueduct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - image: andyleap/aqueduct
        imagePullPolicy: Always
        name: aqueduct
        args:
        - "./server"
        - "--aqueduct=:6476"
        - "--host=:8080"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 6476
          name: aqueduct
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scannerpublic
  namespace: aqueduct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scannerpublic
  template:
    metadata:
      labels:
        app: scannerpublic
    spec:
      containers:
      - image: andyleap/tokenauth
        imagePullPolicy: Always
        name: aqueduct
        args:
        - "./tokenauth"
        - "--token=sedxzawscfvxdcnjmbhn"
        - "--host=http://scanner:8080/"
        ports:
        - containerPort: 8080
          name: http
