apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-gateway-api
  namespace: kargo-gateway-api
spec:
  promotionPolicies:
    - stage: main
      autoPromotionEnabled: true
