apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gateway-api
  namespace: kargo-gateway-api
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/kubernetes-sigs/gateway-api.git
        commitSelectionStrategy: SemVer
        semverConstraint: ">=1.0.0 <2.0.0"
        strictSemvers: true
