apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd
  - cert-manager
  - cert-manager-webhook-linode
  - cluster
  - kargo
  - kargo-projects
  - pocket-id
  - simplelog
  - tinyoauth
  - traefik
  - traefik-crds
