apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-traefik-crds
  namespace: kargo-traefik-crds
spec:
  promotionPolicies:
    - stage: main
      autoPromotionEnabled: true
