apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: traefik-crds
  namespace: kargo-traefik-crds
spec:
  subscriptions:
    - chart:
        repoURL: https://traefik.github.io/charts
        name: traefik-crds
        semverConstraint: ">=1.18.0 <2.0.0"
    - git:
        repoURL: https://github.com/andyleap-cluster/cluster.git
        branch: master
        commitSelectionStrategy: NewestFromBranch
        strictSemvers: false
