apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

images:
- name: ghcr.io/andyleap/passkey-auth-service:latest
  digest: sha256:049ff83d3017ee95615e23552fc8fa9206c45c1f63398fc5f6b36d892bd90658