apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-kargo-projects
  namespace: kargo-kargo-projects
spec:
  promotionPolicies:
    - stage: main
      autoPromotionEnabled: true
