apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-trigger
  namespace: gitserve
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-trigger
  annotations:
    kubernetes.io/service-account.name: argo-trigger
type: kubernetes.io/service-account-token