apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: "kargo-cert-manager:main"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: v1.21.0
      helm:
        valueFiles:
          - $values/cert-manager/values.yaml
    - repoURL: 'https://github.com/andyleap-cluster/cluster.git'
      targetRevision: live
      ref: values
    - repoURL: 'https://github.com/andyleap-cluster/cluster.git'
      targetRevision: live
      path: cert-manager/extras
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
