apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-linode
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/linode/cert-manager-webhook-linode.git'
      targetRevision: v0.3.0
      path: deploy/cert-manager-webhook-linode
      helm:
        valueFiles:
          - $values/cert-manager-webhook-linode/values.yaml
    - repoURL: 'https://github.com/andyleap-cluster/cluster.git'
      targetRevision: master
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
