apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo
  namespace: kargo-kargo
spec:
  subscriptions:
    - chart:
        repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
        semverConstraint: ">=1.0.0 <2.0.0"
    - git:
        repoURL: https://github.com/andyleap-cluster/cluster.git
        branch: master
        commitSelectionStrategy: NewestFromBranch
        strictSemvers: false
        # Only build new Freight when this app's manifests change.
        includePaths:
          - cluster/kargo.yaml
          - kargo
