apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app: database
spec:
  storageClassName: linode-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"