apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vscode
spec:
  serviceName: vscode
  replicas: 1
  selector:
    matchLabels:
      app: vscode
  template:
    metadata:
      labels:
        app: vscode
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: vscode
          image: codercom/code-server:4.2.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: vscode-data
              mountPath: /home/coder
      volumes:
        - name: vscode-data
          persistentVolumeClaim:
            claimName: vscode-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-data
  labels:
    app: vscode
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vscode
  annotations:
    "git.andyleap.dev/singress-target": "vscode.andyleap.dev"
spec:
  selector:
    app: vscode
  ports:
  - name: http
    port: 8080
    targetPort: 8080
