apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
  annotations:
    "git.andyleap.dev/singress-target": "andyleap.dev"
spec:
  selector:
    app: blog
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: ghcr.io/andyleap/blog@sha256:46bcb3963da46a1294908d052d907c2588a19af21dac00d7b15161d1580625f0
        name: blog
        ports:
          - containerPort: 8080
            name: http
        env:
        - name: S3_DOMAIN
          value: us-east-1.linodeobjects.com
        - name: S3_BUCKET
          value: andyleap-dev
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: s3-api-token
              key: key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-api-token
              key: secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: blog-pg
              key: pg