apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
  annotations:
    "git.andyleap.dev/singress-target": "andyleap.dev"
spec:
  selector:
    app: blog
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: ghcr.io/andyleap/blog@sha256:fff9e33441bd5b767f6c7abe3da6400ef1a2dbe42a51c18c829f5f3bc2f16d98
        name: blog
        ports:
          - containerPort: 8080
            name: http
        env:
        - name: S3_DOMAIN
          value: us-east-1.linodeobjects.com
        - name: S3_BUCKET
          value: andyleap-dev
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: s3-api-token
              key: key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-api-token
              key: secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: blog-pg
              key: PG