apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
  annotations:
    "git.andyleap.dev/singress-target": "andyleap.dev"
spec:
  selector:
    app: blog
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: ghcr.io/andyleap/nostr-blog:8d744f411b1a15e9552a226f76a48e5fae94fb73
        name: blog
        ports:
          - containerPort: 8080
            name: http
        env:
          - name: PUB_KEY
            value: "29af6f8a1edf223e0d7db3ab10e7bb1940de3b2ef2be223dec7780f5a8a14814"
          - name: RELAY_URL
            value: relay.relay
