apiVersion: v1
kind: Service
metadata:
  name: blog
  annotations:
    git.andyleap.dev/singress-target: andyleap.dev
spec:
  selector:
    app: blog
  ports:
  - name: http
    port: 8080
    targetPort: 8080