# ArgoCD Helm chart values
# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd

configs:
  params:
    server.insecure: true

extraObjects:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: argocd-tls
      namespace: argocd
    spec:
      secretName: argocd-tls
      issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
      dnsNames:
        - argocd.andyleap.dev

  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: argocd
      namespace: argocd
    spec:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
          sectionName: websecure
      hostnames:
        - argocd.andyleap.dev
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: ""
              kind: Service
              name: argocd-server
              port: 80
              weight: 1

  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: argocd-redirect
      namespace: argocd
    spec:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
          sectionName: web
      hostnames:
        - argocd.andyleap.dev
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          filters:
            - type: RequestRedirect
              requestRedirect:
                scheme: https
                statusCode: 301

  - apiVersion: gateway.networking.k8s.io/v1beta1
    kind: ReferenceGrant
    metadata:
      name: allow-traefik-gateway
      namespace: argocd
    spec:
      from:
        - group: gateway.networking.k8s.io
          kind: Gateway
          namespace: traefik
      to:
        - group: ""
          kind: Secret
          name: argocd-tls
