apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: argocd
  namespace: kargo-argocd
spec:
  subscriptions:
    - chart:
        repoURL: https://argoproj.github.io/argo-helm
        name: argo-cd
        semverConstraint: ">=8.0.0 <10.0.0"
    - git:
        repoURL: https://github.com/andyleap-cluster/cluster.git
        branch: master
        commitSelectionStrategy: NewestFromBranch
        strictSemvers: false
        # Only build new Freight when this app's manifests change.
        includePaths:
          - cluster/argocd.yaml
          - argocd
