apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      securityContext:
        runAsUser: 5984
        runAsGroup: 5984
        fsGroup: 5984
      containers:
      - name: couchdb
        image: couchdb:3.5.0
        ports:
        - name: couchdb
          containerPort: 5984
        env:
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-data