apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: andyleap/static
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: s3-api-token
              key: key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-api-token
              key: secret
        - name: S3_BUCKET
          value: andyleap-static