apiVersion: v1
kind: Service
metadata:
  name: static
  annotations:
    git.andyleap.dev/singress-target: static.andyleap.dev
spec:
  type: ClusterIP
  selector:
    app: static
  ports:
  - name: http
    port: 8080
    targetPort: http