apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: relay
  template:
    metadata:
      labels:
        app: relay
    spec:
      containers:
        - name: relay
          image: ghcr.io/andyleap/nostr/relay:7bb1187ecfcb745863e6b924f174784de18cf303
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: relay-secret
          env:
            - name: PG_HOST
              value: database.database
            - name: PG_USER
              value: relay
            - name: PG_DB
              value: relay
            - name: PUB_KEYS
              value: "29af6f8a1edf223e0d7db3ab10e7bb1940de3b2ef2be223dec7780f5a8a14814"
---
apiVersion: v1
kind: Service
metadata:
  name: relay
  annotations:
    "git.andyleap.dev/singress-target": "relay.andyleap.dev"
spec:
  selector:
    app: relay
  ports:
  - name: http
    port: 8080
    targetPort: 8080