apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-cert-manager
  namespace: kargo-cert-manager
spec:
  promotionPolicies:
    - stage: main
      autoPromotionEnabled: true
