apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: main
  namespace: kargo-cert-manager
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: cert-manager
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: git@github.com:andyleap-cluster/cluster.git
            checkout:
              - branch: master
                path: ./src
              - branch: live
                create: true
                path: ./out
        - uses: git-clear
          config:
            path: ./out/cert-manager
        - uses: copy
          config:
            inPath: ./src/cluster/cert-manager.yaml
            outPath: ./out/cluster/cert-manager.yaml
        - uses: copy
          config:
            inPath: ./src/cert-manager
            outPath: ./out/cert-manager
        - uses: yaml-update
          config:
            path: ./out/cluster/cert-manager.yaml
            updates:
              - key: spec.sources.0.targetRevision
                value: ${{ chartFrom("https://charts.jetstack.io", "cert-manager").Version }}
        - uses: git-commit
          config:
            path: ./out
            message: |
              kargo: bump cert-manager to chart ${{ chartFrom("https://charts.jetstack.io", "cert-manager").Version }}
        - uses: git-push
          config:
            path: ./out
            targetBranch: live
