apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: cert-manager
  namespace: kargo-cert-manager
spec:
  subscriptions:
    - chart:
        repoURL: https://charts.jetstack.io
        name: cert-manager
        semverConstraint: ">=1.16.0 <2.0.0"
    - git:
        repoURL: https://github.com/andyleap-cluster/cluster.git
        branch: master
        commitSelectionStrategy: NewestFromBranch
        strictSemvers: false
        # Only build new Freight when this app's manifests change.
        includePaths:
          - cluster/cert-manager.yaml
          - cert-manager
